import type { NextPage } from "next";
import { GetServerSideProps } from "next";

import Head from "next/head";
import Image from "next/image";
import Chart from "@/components/Chart";
import styles from "@/styles/Home.module.scss";

type Props = {
  prefectures: string[];
};

const Home: NextPage = (props: Props) => {
  const getPeopleData = async (checked: boolean) => {
    console.log(checked);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Prefecture Chart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <div>都道府県別人口推移チャート</div>
      </header>
      <main>
        <div>
          <p>都道府県</p>
          <div>
            {props.prefectures.map((name, index) => {
              return (
                <div className={styles.checkbox} key={index}>
                  <input
                    id={index.toString()}
                    type="checkbox"
                    onChange={(e) => getPeopleData(e.target.checked)}
                  />
                  <label htmlFor={index.toString()}>{name}</label>
                </div>
              );
            })}
          </div>
          <Chart />
        </div>
      </main>
    </div>
  );
};

// サーバー側で都道府県の情報は取得
export const getServerSideProps: GetServerSideProps = async (context) => {
  const API_KEY: any = process.env.NEXT_PUBLIC_API_KEY;
  let prefectures: string[] = [];

  const urlPrefectures = "https://opendata.resas-portal.go.jp/api/v1/prefectures";

  await fetch(urlPrefectures, {
    headers: {
      "X-API-KEY": API_KEY,
    },
  })
    .then((res) => {
      if (res.ok) {
        return res.json();
      }
      throw new Error(`Some Error`);
    })
    .then((data) => {
      prefectures = data.result.map(
        (item: { prefCode: number; prefName: string }) => item.prefName,
      );
    })
    .catch((err) => {
      // エラーが発生した場合
      console.error(err);
    });
  const props: Props = {
    prefectures: prefectures,
  };

  return {
    props: props,
  };
};

export default Home;
